// Verified: 12 reachable states. Generated by #TLASpec macro.
struct HourClock: Equatable, Hashable {
    var hr: Int
    init(hr: Int) { self.hr = hr }
    static let initial = HourClock(hr: 1)
    
    enum Action: CaseIterable { case tick }
    
    var transitions: [(Action, HourClock)] {
        switch hr {
        case 1:  return [(.tick, HourClock(hr: 2))]
        case 2:  return [(.tick, HourClock(hr: 3))]
        case 3:  return [(.tick, HourClock(hr: 4))]
        case 4:  return [(.tick, HourClock(hr: 5))]
        case 5:  return [(.tick, HourClock(hr: 6))]
        case 6:  return [(.tick, HourClock(hr: 7))]
        case 7:  return [(.tick, HourClock(hr: 8))]
        case 8:  return [(.tick, HourClock(hr: 9))]
        case 9:  return [(.tick, HourClock(hr: 10))]
        case 10: return [(.tick, HourClock(hr: 11))]
        case 11: return [(.tick, HourClock(hr: 12))]
        case 12: return [(.tick, HourClock(hr: 1))]
        default: return []
        }
    }
    
    var availableActions: [Action] { transitions.map(\.0) }
    mutating func apply(_ action: Action) {
        guard let next = transitions.first(where: { $0.0 == action })?.1 else { return }
        self = next
    }
}
